# vim:ft=yaml.ansible
---
- name: "Check existance of {{ lazydocker_path }}"
  ansible.builtin.stat:
    path: "{{ lazydocker_path }}"
  register: binary_register
  tags: lazydocker

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ binary_register.stat.path }} version | grep Version | cut -f2 -d ' '
  args:
    executable: /bin/bash
  register: version_register
  changed_when: false
  when: binary_register.stat.exists
  tags: lazydocker

- name: Set install variables
  ansible.builtin.set_fact:
    lazydocker_installed: "{{ binary_register.stat.exists }}"
    lazydocker_installed_version: "{{ version_register.stdout | default(False) }}"
  tags: lazydocker

- name: Install
  become: true
  tags: lazydocker
  when: not lazydocker_installed or lazydocker_installed_version != lazydocker_version
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ lazydocker_url }}"
        dest: /tmp
        checksum: "{{ lazydocker_checksum | default(omit) }}"
        mode: "0644"

    - name: Unarchive
      ansible.builtin.unarchive:
        src: "/tmp/{{ lazydocker_archive }}"
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/lazydocker
        dest: "{{ lazydocker_path }}"
        mode: "0755"
        remote_src: true
