---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ adguardhome_path }}"
  register: adguardhome_binary_register
  tags: adguardhome

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ adguardhome_binary_register.stat.path }} --version | grep -oP 'v\K[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  register: adguardhome_version_register
  changed_when: false
  when: adguardhome_binary_register.stat.exists
  tags: adguardhome

- block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ adguardhome_url }}"
        checksum: "{{ adguardhome_checksum | default(omit) }}"
        dest: /tmp/adguardhome.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/adguardhome.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/AdGuardHome/AdGuardHome
        dest: "{{ adguardhome_path }}"
        mode: 0755
        remote_src: true
      notify: restart adguardhome

  become: true
  tags: adguardhome
  when: not adguardhome_binary_register.stat.exists or (adguardhome_version_register.stdout | default('')) != adguardhome_version
