---
scrutiny_collector_packages:
  - smartmontools
scrutiny_collector_architectures:
  aarch64: arm64
  armv5l: arm-5
  armv6l: arm-6
  armv7l: arm-7
  x86_64: amd64
scrutiny_collector_version: "{{ undef(hint='Specify version (e.g. 0.5.0)') }}"
scrutiny_collector_platform: "{{ ansible_system | lower }}-{{ scrutiny_collector_architectures[ansible_architecture] }}"
scrutiny_collector_url: "https://github.com/AnalogJ/scrutiny/releases/download/v{{ scrutiny_collector_version }}/scrutiny-collector-metrics-{{ scrutiny_collector_platform }}"
# scrutiny_collector_checksum:
scrutiny_collector_path: /usr/local/bin/scrutiny-collector-metrics

scrutiny_collector_command: "{{ scrutiny_collector_path }} run --api-endpoint={{ scrutiny_collector_api_endpoint }} --host-id={{ scrutiny_collector_host_id }}"

scrutiny_collector_cron: false
scrutiny_collector_cron_minute: "0"
scrutiny_collector_cron_hour: "*"
scrutiny_collector_cron_month: "*"
scrutiny_collector_cron_weekday: "*"

scrutiny_collector_api_endpoint: http://localhost:8080
scrutiny_collector_host_id: ""

scrutiny_collector_systemd: false
scrutiny_collector_systemd_on_calendar: hourly
