# vim:ft=yaml.ansible
---
- name: Install sanoid
  ansible.builtin.apt:
    name:
      - anacron
      - sanoid
    state: present
  become: true
  tags: sanoid

- name: "Create {{ sanoid_config_dir }}"
  ansible.builtin.file:
    path: "{{ sanoid_config_dir }}"
    state: directory
    mode: "0755"
  become: true
  tags: sanoid

- name: Configure sanoid
  ansible.builtin.copy:
    src: "{{ sanoid_config | default(omit) }}"
    content: "{{ sanoid_config_content | default(omit) }}"
    dest: "{{ sanoid_config_file }}"
    mode: "0644"
  when: sanoid_config is defined or sanoid_config_content is defined
  become: true
  tags: sanoid
