# vim:ft=yaml.ansible
---
- name: Install sanoid
  ansible.builtin.apt:
    name:
      - anacron
      - sanoid
    state: present
  become: true
  tags: sanoid

- name: "Create {{ sanoid_path_config }}"
  ansible.builtin.file:
    path: "{{ sanoid_path_config }}"
    state: directory
    mode: "0755"
  become: true
  tags: sanoid

- name: Configure sanoid
  ansible.builtin.copy:
    content: "{{ sanoid_config }}"
    dest: "{{ sanoid_file_config }}"
    mode: "0644"
  when: sanoid_config is defined
  become: true
  tags: sanoid
