# vim:ft=yaml.ansible
---
- name: Install packages
  ansible.builtin.package:
    name: "{{ mediamtx_packages }}"
    state: present
  become: true
  tags: mediamtx

- name: Create user
  ansible.builtin.user:
    name: "{{ mediamtx_user }}"
  become: true
  tags: mediamtx

- name: Import install
  ansible.builtin.import_tasks: install.yml

- name: Template service
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/mediamtx.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart mediamtx
  tags: mediamtx

- name: Enable service
  ansible.builtin.systemd:
    name: mediamtx
    enabled: true
  become: true
  tags: mediamtx

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: mediamtx
