---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ kopia_path }}"
  register: kopia_binary_register
  tags: kopia

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ kopia_binary_register.stat.path }} --version
  args:
    executable: /bin/bash
  register: kopia_version_register
  changed_when: false
  when: kopia_binary_register.stat.exists
  tags: kopia

- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ kopia_url }}"
        checksum: "{{ kopia_checksum | default(omit) }}"
        dest: /tmp/kopia.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/kopia.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: "/tmp/kopia-{{ kopia_version }}-{{ kopia_platform }}/kopia"
        dest: "{{ kopia_path }}"
        mode: 0755
        remote_src: true

  become: true
  tags: kopia
  when: not kopia_binary_register.stat.exists or kopia_version not in (kopia_version_register.stdout | default(''))
