# vim:ft=yaml.ansible
---
- name: Install nfs
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"
  become: true
  tags: nfs

- name: Copy export config
  ansible.builtin.copy:
    src: "{{ nfs_config_local | default(omit) }}"
    content: "{{ nfs_config_content | default(omit) }}"
    dest: "/etc/exports"
    mode: "644"
  when: nfs_config_local is defined or nfs_config_content is defined
  notify: Restart nfs
  become: true
  tags: nfs

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: nfs
