---
- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ blocky_url }}"
        checksum: "{{ blocky_checksum | default(omit) }}"
        dest: /tmp/blocky.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/blocky.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/blocky
        dest: "{{ blocky_path }}"
        mode: 0755
        remote_src: true
      notify: restart blocky

    - name: Create facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Update facts
      ansible.builtin.copy:
        content: "{{ blocky_facts | to_nice_json }}"
        dest: /etc/ansible/facts.d/blocky.fact
        owner: root
        group: root
        mode: 0644

  become: true
  tags: blocky
  when: ansible_facts.ansible_local['blocky'] is not defined or (ansible_facts.ansible_local.blocky.version | string) != (blocky_version | string)
