---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ blocky_path }}"
  register: blocky_binary_register
  tags: blocky

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ blocky_binary_register.stat.path }} version | grep -oP 'Version: \K[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  register: blocky_version_register
  changed_when: false
  when: blocky_binary_register.stat.exists
  tags: blocky

- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ blocky_url }}"
        checksum: "{{ blocky_checksum | default(omit) }}"
        dest: /tmp/blocky.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/blocky.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/blocky
        dest: "{{ blocky_path }}"
        mode: 0755
        remote_src: true
      notify: restart blocky

  become: true
  tags: blocky
  when: not blocky_binary_register.stat.exists or (blocky_version_register.stdout | default('')) != (blocky_version | string)
