---
- name: Create user
  ansible.builtin.user:
    name: "{{ blocky_user }}"
  become: true
  tags: blocky

- import_tasks: install.yml

- name: Template service
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/blocky.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart blocky
  tags: blocky

- name: Enable service
  ansible.builtin.systemd:
    name: blocky
    enabled: true
  become: true
  tags: blocky

- name: Copy config
  ansible.builtin.copy:
    content: "{{ blocky_config | to_nice_yaml }}"
    dest: "{{ blocky_config_path }}"
    owner: "{{ blocky_user }}"
    group: "{{ blocky_group }}"
    mode: 0600
  become: true
  notify: restart blocky
  tags: blocky

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: blocky
