---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ scrutiny_collector_path }}"
  register: scrutiny_collector_binary_register
  tags: scrutiny_collector

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ scrutiny_collector_path }} --version 2> /dev/null | grep -oP '\K[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  changed_when: false
  register: scrutiny_collector_version_register
  tags: scrutiny_collector
  when: scrutiny_collector_binary_register.stat.exists

- name: Download and install
  ansible.builtin.get_url:
    checksum: "{{ scrutiny_collector_checksum | default(omit) }}"
    dest: "{{ scrutiny_collector_path }}"
    url: "{{ scrutiny_collector_url }}"
    mode: 0755
  become: true
  tags: scrutiny_collector
  when: not scrutiny_collector_binary_register.stat.exists or (scrutiny_collector_version_register.stdout | default('')) != scrutiny_collector_version

- name: Add scrutiny_collector to cron
  ansible.builtin.cron:
    name: "scrutiny_collector cron"
    minute: "{{ scrutiny_collector_cron_minute }}"
    hour: "{{ scrutiny_collector_cron_hour }}"
    month: "{{ scrutiny_collector_cron_month }}"
    weekday: "{{ scrutiny_collector_cron_weekday }}"
    job: "{{ scrutiny_collector_path }} run --api-endpoint={{ scrutiny_collector_api_endpoint }} --host-id={{ scrutiny_collector_host_id }}"
  become: true
  tags: scrutiny_collector
  when: scrutiny_collector_cron | bool
