---
go2rtc_packages:
  - ffmpeg
go2rtc_architectures:
  arm64: arm64
  armv6l: armv6
  armv7l: armv6
  i386: i386
  x86_64: amd64
go2rtc_platform: "{{ ansible_system | lower }}_{{ go2rtc_architectures[ansible_architecture] }}"
go2rtc_version: "{{ undef(hint='Specify version (e.g. 1.7.0)') }}"
go2rtc_url: "https://github.com/AlexxIT/go2rtc/releases/download/v{{ go2rtc_version }}/go2rtc_{{ go2rtc_platform }}"
# go2rtc_checksum:
go2rtc_path: /usr/local/bin/go2rtc
go2rtc_user: go2rtc
go2rtc_group: "{{ go2rtc_user }}"
go2rtc_dir: "/home/{{ go2rtc_user }}"
