---
- name: Install packages
  ansible.builtin.package:
    name: "{{ msmtp_packages }}"
    state: present
  become: true
  tags: msmtp

- name: Copy config
  ansible.builtin.copy:
    content: "{{ msmtp_config }}"
    dest: /etc/msmtprc
    owner: "{{ msmtp_user }}"
    group: "{{ msmtp_group }}"
    mode: 0600
  become: true
  tags: msmtp
  when: msmtp_config is defined
