---
- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ traefik_url }}"
        checksum: "{{ traefik_checksum | default(omit) }}"
        dest: /tmp/traefik.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/traefik.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: "/tmp/traefik"
        dest: "{{ traefik_path }}"
        mode: 0755
        remote_src: true

    - name: Create facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Update facts
      ansible.builtin.copy:
        content: "{{ traefik_facts | to_nice_json }}"
        dest: /etc/ansible/facts.d/traefik.fact
        owner: root
        group: root
        mode: 0644

  become: true
  tags: traefik
  when: ansible_facts.ansible_local['traefik'] is not defined or (ansible_facts.ansible_local.traefik.version | string) != (traefik_version | string)
