---
- name: Check if already installed
  ansible.builtin.stat:
    path: "{{ croc_path }}"
  register: croc_binary_register
  tags: croc

- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    {{ croc_binary_register.stat.path }} --version
  args:
    executable: /bin/bash
  register: croc_version_register
  changed_when: false
  when: croc_binary_register.stat.exists
  tags: croc

- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ croc_url }}"
        checksum: "{{ croc_checksum | default(omit) }}"
        dest: /tmp/croc.tar.gz
        mode: 0644

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/croc.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install
      ansible.builtin.copy:
        src: /tmp/croc
        dest: "{{ croc_path }}"
        mode: 0755
        remote_src: true

  become: true
  tags: croc
  when: not croc_binary_register.stat.exists or (croc_version_register.stdout | default('')) != croc_version
