---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags: icecast

- name: Install icecast
  ansible.builtin.package:
    name: "{{ icecast_package }}"
    state: present
  become: true
  tags: icecast

- name: Copy config file
  ansible.builtin.copy:
    content: "{{ icecast_config }}"
    dest: "{{ icecast_path_config }}"
  become: true
  notify: restart icecast
  tags: icecast
  when: icecast_config is defined

- name: Enable and start icecast
  ansible.builtin.service:
    name: "{{ icecast_service }}"
    enabled: true
    state: started
  become: true
  tags: icecast
