---
adguardhomesync_architectures:
  arm64: arm64
  armv5l: armv5
  armv6l: armv6
  armv7l: armv7
  i386: i386
  x86_64: x86_64
adguardhomesync_platform: "{{ ansible_system | lower }}_{{ adguardhomesync_architectures[ansible_architecture] }}"
adguardhomesync_version: 0.4.3
adguardhomesync_url: "https://github.com/bakito/adguardhome-sync/releases/download/v{{ adguardhomesync_version }}/adguardhome-sync_{{ adguardhomesync_version }}_{{ adguardhomesync_platform }}.tar.gz"
# adguardhomesync_checksum: sha256:
adguardhomesync_path: /usr/local/bin/adguardhome-sync
adguardhomesync_user: adguardhome-sync
adguardhomesync_group: "{{ adguardhomesync_user }}"
adguardhomesync_config_dir: "/home/{{ adguardhomesync_user }}"
# adguardhomesync_config:
#   # cron expression to run in daemon mode. (default; "" = runs only once)
#   cron: "*/10 * * * *"
#
#   # runs the synchronisation on startup
#   runOnStart: true
#
#   origin:
#     # url of the origin instance
#     url: https://192.168.1.2:3000
#     # apiPath: define an api path if other than "/control"
#     # insecureSkipVerify: true # disable tls check
#     username: username
#     password: password
#
#   # replica instance (optional, if only one)
#   replica:
#     # url of the replica instance
#     url: http://192.168.1.3
#     username: username
#     password: password
#
#   # replicas instances (optional, if more than one)
#   replicas:
#     # url of the replica instance
#     - url: http://192.168.1.3
#       username: username
#       password: password
#     - url: http://192.168.1.4
#       username: username
#       password: password
#       # autoSetup: true # if true, AdGuardHome is automatically initialized.
#
#   # Configure the sync API server, disabled if api port is 0
#   api:
#     # Port, default 8080
#     port: 8080
#     # if username and password are defined, basic auth is applied to the sync API
#     username: username
#     password: password
#
#   # Configure sync features; by default all features are enabled.
#   features:
#     generalSettings: true
#     queryLogConfig: true
#     statsConfig: true
#     clientSettings: true
#     services: true
#     filters: true
#     dhcp:
#       serverConfig: true
#       staticLeases: true
#     dns:
#       serverConfig: true
#       accessLists: true
#       rewrites: true
