---
- name: Create user
  ansible.builtin.user:
    name: "{{ gatus_user }}"
  become: true
  tags: gatus

- name: Template service
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/gatus.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart gatus
  tags: gatus

- name: Enable service
  ansible.builtin.systemd:
    name: gatus
    enabled: true
  become: true
  tags: gatus

- name: Copy config
  ansible.builtin.copy:
    content: "{{ gatus_config | to_nice_yaml }}"
    dest: "{{ gatus_config_path }}"
    owner: "{{ gatus_user }}"
    group: "{{ gatus_group }}"
    mode: 0600
  become: true
  tags: gatus

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: gatus
