---
- name: Get installed version
  ansible.builtin.shell: |
    set -o pipefail
    (dpkg-query -s neovim || echo "Version: 1.0.0") | grep Version: | cut -f2 -d ' '
  args:
    executable: /bin/bash
  changed_when: false
  register: neovim_version_register
  tags: neovim

- name: Install
  block:
    - name: Download
      ansible.builtin.get_url:
        url: "{{ neovim_url_deb }}"
        checksum: "{{ neovim_checksum_deb | default(omit) }}"
        dest: /tmp/nvim-linux64.deb
        mode: 0644

    - name: Install
      ansible.builtin.apt:
        deb: /tmp/nvim-linux64.deb

  become: true
  tags: neovim
  when: neovim_version_register.stdout != neovim_version
